name = "weloveyou"
author = "heavywinds"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c0978c49b6fcca9e7d2aa9d58d0f64d063ec6ae74255dd8ff772792bc98e385"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
