name = "weloveyou"
author = "heavywinds"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5098934d3ad20681b21656ec96b7ceb62aac6a110833d5f4fe0271aba870e34c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
