name = "weloveyou"
author = "heavywinds"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef0dae54805b43582d0d188399a6b22a3e805c26d72ad00c0b78cf5f9c818182"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
